### ISSUE TITLE
BREAKING CHANGE: Use `vim.ui.input` API core

### ISSUE THREAD

**Issue by aspeddro** [filipdutescu/renamer.nvim#102]
Neovim 0.6.0 added [`vim.ui.input`](https://github.com/neovim/neovim/pull/15959). Could it be a good alternative to reduce dependencies

**Comment by filipdutescu** [comment]
Yes, I know about it, but I decide against migrating to it, since for previous versions it would not be possible and for that component I would not receive the LSP response needed for setting the quickfix list and putting the cursor at the word end.

If you, or anyone for that matter, know by any chance how I could make that work I have nothing against it. Otherwise I will keep the current implementation.

**Comment by axieax** [comment]
Not sure if this helps, but here is what I'm doing for my personal config:
- Defining a custom handler for setting qflist and nvim-notify (optional) [here](https://github.com/axieax/dotconfig/blob/main/nvim/lua/lsp/rename.lua)
- Attaching this handler to lspconfig server setup options [here](https://github.com/axieax/dotconfig/blob/9153fc01e175490e747a8a224c827ce751bcf857/nvim/lua/lsp/install.lua#L187-L189)

**Comment by filipdutescu** [comment]
Wait, @axieax, it sends the response? This is new, I am pretty sure it didn't the first time `vim.ui.input` was added. My other concern is that it doesn't seem to be able to handle responsiveness very well. What happens when the width of the window is too small? What does it happen when the height is too small?

This would also make it kind of hard to maintain for Neovim < `0.6.0`, I think :thinking:. What do you both think?

**Comment by axieax** [comment]
Forgot to mention, but I'm also using [dressing.nvim](https://github.com/stevearc/dressing.nvim) for customising the look of my `vim.ui.input`. With this, it seems that the window content autoscrolls if it doesn't fit. But yeah this most likely wouldn't be supported by earlier versions haha

**Comment by filipdutescu** [comment]
The thing is, if I want to style the UI, most likely I will still need to use `plenary` or another dependency. The only advantage I see is that I wouldn't need to make the LSP requests myself.

Honestly, it seems to bring too few advantages at the moment, when taking into account the effort needed (talking about docs and tests mostly). Will leave open, if anyone wants to take it upon themselves I can take a look and provide feedback, but I don't think it is worth it for me, personally, to put the effort in, when the existing solution works, has good docs (in my opinion) and a nice set of tests.

**Comment by filipdutescu** [comment]
I am considering migrating to the Neovim 0.6.0 API, but I think I will wait a bit more, for more time to pass to ensure most people migrated to this Neovim version. If it proves to be a lot of work I might not implement it, since the current solution works perfectly in my opinion, but it might help with not needing to handle LSP requests myself.

**Comment by aspeddro** [comment]
After some thought, I think this approach is not good. `vim.ui.select` should be managed by plugins which change the default style by overriding the function, like https://github.com/rcarriga/nvim-notify does.

Feel free to close this issue.

**Comment by filipdutescu** [comment]
Closing this as the new implementation I have written will not use the `vim.ui.input` method, since at the moment it seems more complex than needed, compared to what I have done in GH-122
