### ISSUE TITLE
How to map `<C-c>` to `<Esc>`

### ISSUE THREAD

**Issue by DEliasVCruz** [filipdutescu/renamer.nvim#91]
When using `<C-c>` inside of the renamer window it will execute the default
**clear line** and I've tried to **remapping so** as that it will **close the
renamer window** like so:

```lua
  use {
    "filipdutescu/renamer.nvim",
    branch = "master",
    module = "renamer",
    config = function()
      local mappings_utils = require "renamer.mappings.utils"
      require("renamer").setup {
        mappings = {
          ["<c-e>"] = mappings_utils.set_cursor_to_end,
          ["<c-c>"] = "<Esc>",
          ["<c-u>"] = mappings_utils.clear_line,
        },
      }
    end,
  }
```

But is not working. So I was wondering what is the correct way

Thanks in advance.

**Comment by filipdutescu** [comment]
Thanks for submitting your question!

First of all, I am sorry for your confusion and for the inconvenience. It is clear that I failed to properly document how to add mappings. I ask you, even when we fix your issue, to please leave this issue open, in order for me to track the required changes to docs.

Secondly, the issue is that keymaps should have for value a function, not a string (as you've set `<esc>`). What you should do is something similar to the way I created mappings, in `lua/renamer/mappings/utils.lua`. Most likely you wish for:

```lua
-- other code...

['<c-c>'] = function()
    vim.api.nvim_input('<esc>')
end

-- other code...
```
